name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: 'file:./dev.db'

jobs:
  testing:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: svelte-check
        run: pnpm run check

      - name: pretter & eslint
        run: pnpm run lint

      - name: vitest
        run: pnpm run test:unit -- --run

      - name: setup playwright
        run: |
          pnpx playwright install --with-deps
          pnpx playwright install-deps

      - name: setup prisma
        run: pnpx prisma db push

      - name: playwright
        run: pnpx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
