name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: 'file:./dev.db'

jobs:
  testing:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci

      - name: svelte-check
        run: npm run check

      - name: pretter & eslint
        run: npm run lint

      - name: vitest
        run: npm run test:unit -- --run

      - name: setup playwright
        run: npx playwright install --with-deps
        run: npx playwright install-deps

      - name: setup prisma
        run: npx prisma db push

      - name: playwright
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
